# Generated by Django 4.1.7 on 2023-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('AIML', 'AIML'), ('AIDS', 'AIDS'), ('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ME', 'ME'), ('MAE', 'MAE'), ('CIVIL', 'CIVIL'), ('BA-LLB', 'BA-LLB'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=30)),
            ],
        ),
    ]
