# Generated by Django 4.1.7 on 2023-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Director', 'Director'), ('CEO', 'CEO'), ('Owner', 'Owner'), ('HOD', 'HOD'), ('DI', 'DI'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Student', 'Student'), ('MM', 'MM')], max_length=50),
        ),
    ]
