# Generated by Django 4.1.7 on 2023-10-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmenant_managnement', '0002_alter_department_name'),
        ('accounts', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departmenant_managnement.department'),
        ),
    ]
