# Generated by Django 4.1.7 on 2023-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenanceType', models.CharField(choices=[('Civil', 'Civil'), ('Water', 'Water'), ('Electric', 'Electric')], max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Hold', 'Hold'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
    ]
