# Generated by Django 4.1.7 on 2023-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0002_maintenanceissue_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
