# Generated by Django 4.1.7 on 2023-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0004_maintenanceissue_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
