# Generated by Django 4.1.7 on 2023-10-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmenant_managnement', '0002_alter_department_name'),
        ('maintenance_management', '0005_alter_maintenanceissue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departmenant_managnement.department'),
        ),
        migrations.AlterField(
            model_name='maintenanceissue',
            name='maintenanceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance_management.maintenancetype'),
        ),
    ]
