# Generated by Django 4.1.7 on 2023-10-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0006_maintenancetype_maintenanceissue_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceissue',
            name='timestamp',
            field=models.DateField(auto_created=True, auto_now=True, null=True),
        ),
    ]
